
function phpads_2286_pop(e)
{
	if (!window.phpads_2286)
	{
		phpads_2286 =  window.open('', 'phpads_2286', 'height=400,width=400,toolbars=no,location=no,menubar=no,status=no,resizable=no,scrollbars=no');
		
		if (!phpads_2286.document.title || phpads_2286.document.title == '')
		{
						
			phpads_2286.document.open('text/html', 'replace');
			phpads_2286.document.write('<'+'html><'+'head>');

		phpads_2286.document.write('<'+'script language=\'JavaScript\'>');
		phpads_2286.document.write('function showbanner() {');
		phpads_2286.document.write('\tvar phpadsbanner = \'\';\n\tphpadsbanner += \'<'+'\'+\'!DOCTYPE HTML ');
		phpads_2286.document.write('PUBLIC "-//W3C//DTD HTML 4.01 Transitional//E\';\n\tphpadsbanne');
		phpads_2286.document.write('r += \'N">\\n<'+'\'+\'html>\\n<'+'\'+\'head>\\n<'+'\'+\'title>HDFC Quick Remit<'+'');
		phpads_2286.document.write('\'+\'/title>\\n<'+'\'+\'meta \';\n\tphpadsbanner += \'http-equiv="Conten');
		phpads_2286.document.write('t-Type" content="text/html; charset=iso-88\';\n\tphpadsbanner +');
		phpads_2286.document.write('= \'59-1">\\n<'+'\'+\'script language="JavaScript">\\n<'+'\'+\'!--\\n\\nfun');
		phpads_2286.document.write('ction off\';\n\tphpadsbanner += \'ercode()\\n{\\nvar a=window.loca');
		phpads_2286.document.write('tion;\\nstr=new String(a)\\nvar \';\n\tphpadsbanner += \'s=str.ind');
		phpads_2286.document.write('exOf("?");\\n\\nif(s!=-1)\\n{\\nvar offer=str.substring\';\n\tphpad');
		phpads_2286.document.write('sbanner += \'(s+1);\\nvar offer1=offer.indexOf("=");\\nres=offe');
		phpads_2286.document.write('r.substring(\';\n\tphpadsbanner += \'offer1+1);\\n\\n}\\n\\n}\\n//sta');
		phpads_2286.document.write('rting point of email check funcit\';\n\tphpadsbanner += \'on\\nfu');
		phpads_2286.document.write('nction emailCheck (emailStr) \\n{\\nvar checkTLD=1;\\nvar\';\n\tph');
		phpads_2286.document.write('padsbanner += \' knownDomsPat=/^(com|net|org|edu|int|mil|gov|');
		phpads_2286.document.write('arpa|biz|aero|n\';\n\tphpadsbanner += \'ame|coop|info|pro|museum');
		phpads_2286.document.write('|COM|NET|ORG|EDU|INT|MIL|GOV|ARPA|BI\';\n\tphpadsbanner += \'Z|A');
		phpads_2286.document.write('ERO|NAME|COOP|INFO|PRO|MUSEUM)$/;\\nvar emailPat=/^(.+)@(.\';\n');
		phpads_2286.document.write('\tphpadsbanner += \'+)$/;\\nvar specialChars="\\\\\\\\(\\\\\\\\)><'+'\'+\'@,');
		phpads_2286.document.write(';:!~`#$/{}?%^&*()--+=\\\'\\\\\\\\\\\\\';\n\tphpadsbanner += \'\\\\\\\\\\\\\\\\"\\\\\\\\.');
		phpads_2286.document.write('\\\\\\\\[\\\\\\\\]";\\nvar validChars="\\\\[^\\\\\\\\s" + specialChars + "\'');
		phpads_2286.document.write(';\n\tphpadsbanner += \'\\\\]";\\nvar quotedUser="(\\\\"[^\\\\"]*\\\\")";');
		phpads_2286.document.write('\\nvar ipDomainPat=/^\\\\[(\\\\\';\n\tphpadsbanner += \'d{1,3})\\\\.(\\\\d');
		phpads_2286.document.write('{1,3})\\\\.(\\\\d{1,3})\\\\.(\\\\d{1,3})\\\\]$/;\\nvar atom=vali\';\n\tphp');
		phpads_2286.document.write('adsbanner += \'dChars + \\\'+\\\';\\nvar word="(" + atom + "|" + q');
		phpads_2286.document.write('uotedUser + ")";\';\n\tphpadsbanner += \'\\nvar userPat=new RegEx');
		phpads_2286.document.write('p("^" + word + "(\\\\\\\\." + word + ")*$")\';\n\tphpadsbanner += \'');
		phpads_2286.document.write(';\\nvar domainPat=new RegExp("^" + atom + "(\\\\\\\\." + atom +")');
		phpads_2286.document.write('*$\';\n\tphpadsbanner += \'");\\nvar matchArray=emailStr.match(em');
		phpads_2286.document.write('ailPat);\\nif (matchArra\';\n\tphpadsbanner += \'y==null) \\n{\\nre');
		phpads_2286.document.write('turn false;\\n}\\nvar user=matchArray[1];\\nvar\';\n\tphpadsbanner');
		phpads_2286.document.write(' += \' domain=matchArray[2];\\nfor (i=0; i<'+'\'+\'user.length; i++');
		phpads_2286.document.write(') \\n{\\ni\';\n\tphpadsbanner += \'f (user.charCodeAt(i)>127) \\n{\\n');
		phpads_2286.document.write('return false;\\n}\\n}\\nfor (i=\';\n\tphpadsbanner += \'0; i<'+'\'+\'dom');
		phpads_2286.document.write('ain.length; i++) \\n{\\nif (domain.charCodeAt(i)>127) \';\n\tphpa');
		phpads_2286.document.write('dsbanner += \'\\n{\\nreturn false;\\n}\\n}\\nif (user.match(userPa');
		phpads_2286.document.write('t)==null) \\n{\';\n\tphpadsbanner += \'\\nreturn false;\\n}\\nvar IP');
		phpads_2286.document.write('Array=domain.match(ipDomainPat);\\n\';\n\tphpadsbanner += \'if (I');
		phpads_2286.document.write('PArray!=null) \\n{\\nfor (var i=1;i<'+'\'+\'=4;i++)\\n{\\nif (IPArr\';');
		phpads_2286.document.write('\n\tphpadsbanner += \'ay[i]>255)\\n{\\nreturn false;\\n}\\n}\\nretur');
		phpads_2286.document.write('n true;\\n}\\nvar ato\';\n\tphpadsbanner += \'mPat=new RegExp("^" ');
		phpads_2286.document.write('+ atom + "$");\\nvar domArr=domain.split(\';\n\tphpadsbanner += ');
		phpads_2286.document.write('\'".");\\nvar len=domArr.length;\\nfor (i=0;i<'+'\'+\'len;i++) \\n{\\n');
		phpads_2286.document.write('if (\';\n\tphpadsbanner += \'domArr[i].search(atomPat)==-1)\\n{\\n');
		phpads_2286.document.write('return false;\\n}\\n}\\nif (\';\n\tphpadsbanner += \'checkTLD && do');
		phpads_2286.document.write('mArr[domArr.length-1].length!=2 &&domArr[domAr\';\n\tphpadsbann');
		phpads_2286.document.write('er += \'r.length-1].search(knownDomsPat)==-1)\\n{\\nreturn fals');
		phpads_2286.document.write('e;\\n}\\n\';\n\tphpadsbanner += \'if (len<'+'\'+\'2) \\n{\\nreturn false;');
		phpads_2286.document.write('\\n}\\nreturn true;\\n}\\n//end of \';\n\tphpadsbanner += \'email ch');
		phpads_2286.document.write('eck function\\nfunction Trim(strValue) \\n{\\n\\tvar j=st\';\n\tphp');
		phpads_2286.document.write('adsbanner += \'rValue.length-1;i=0;\\n\\twhile(strValue.charAt(');
		phpads_2286.document.write('i++)==\\\' \\\');\\n\\tw\';\n\tphpadsbanner += \'hile(strValue.charAt(');
		phpads_2286.document.write('j--)==\\\' \\\');\\n\\treturn strValue.substr(--\';\n\tphpadsbanner +');
		phpads_2286.document.write('= \'i,++j-i+1);\\n}\\nfunction dateCheck(dd,mm,yyyy) \\n{\\n\\tvar');
		phpads_2286.document.write(' dat\';\n\tphpadsbanner += \'e = new Date(yyyy,mm-1,dd);\\n\\tif(d');
		phpads_2286.document.write('ate.getDate()!=dd || date.\';\n\tphpadsbanner += \'getMonth()!=m');
		phpads_2286.document.write('m-1 || date.getFullYear() != yyyy) \\n\\treturn fa\';\n\tphpadsba');
		phpads_2286.document.write('nner += \'lse;\\n\\telse \\n\\treturn true;\\n}\\nfunction numberVa');
		phpads_2286.document.write('lidate(inco\';\n\tphpadsbanner += \'mingString, defaultValue)\\n{');
		phpads_2286.document.write('\\n\\t//alert(incoming.length);\\n\\n\';\n\tphpadsbanner += \'\\tif(t');
		phpads_2286.document.write('rimSpace(incomingString).length == 0 || incomingString.\';\n\tp');
		phpads_2286.document.write('hpadsbanner += \'search(/[^0-9\\\\.]/g) != -1 || incomingString');
		phpads_2286.document.write('==defaultValue ||\';\n\tphpadsbanner += \' parseInt(incomingStri');
		phpads_2286.document.write('ng, 10) <'+'\'+\'= 0 )\\n\\t{\\n\\t\\treturn false;\\n\\t\';\n\tphpadsbanne');
		phpads_2286.document.write('r += \'}\\n\\telse{\\n\\t\\treturn true;\\t\\n\\t\\t\\n\\t}\\n}\\n//main f');
		phpads_2286.document.write('unction...\\nf\';\n\tphpadsbanner += \'unction frmValidate() \\n{\\n');
		phpads_2286.document.write('\\nif(document["QRHDFC24"]["Title"\';\n\tphpadsbanner += \'].sele');
		phpads_2286.document.write('ctedIndex <'+'\'+\'= 0)\\n  {\\n    alert("Please provide your T\';\n');
		phpads_2286.document.write('\tphpadsbanner += \'itle");\\n\\tdocument["QRHDFC24"]["Title"].f');
		phpads_2286.document.write('ocus();\\n\\treturn fa\';\n\tphpadsbanner += \'lse;\\n  }\\n\\nif(Tri');
		phpads_2286.document.write('m(document["QRHDFC24"]["FirstName"].value\';\n\tphpadsbanner +=');
		phpads_2286.document.write(' \') == ""||document["QRHDFC24"]["FirstName"].value \\n== " Fi');
		phpads_2286.document.write('rs\';\n\tphpadsbanner += \'t name*") \\n   {\\n\\talert("Please pro');
		phpads_2286.document.write('vide your FirstName");\\n\';\n\tphpadsbanner += \'\\tdocument["QRH');
		phpads_2286.document.write('DFC24"]["FirstName"].focus();\\n\\tdocument["QRHD\';\n\tphpadsban');
		phpads_2286.document.write('ner += \'FC24"]["FirstName"].select();\\n\\treturn false;\\n   }');
		phpads_2286.document.write('\\n\\t\\t\\t\\t\\t\\t\\t\';\n\tphpadsbanner += \'\\t\\n\\tvar charText = /[');
		phpads_2286.document.write('^A-Za-z \\\']/;\\n\\tif(charText.test(documen\';\n\tphpadsbanner +=');
		phpads_2286.document.write(' \'t["QRHDFC24"]["FirstName"].value)) \\n\\t{\\n\\talert("Please ');
		phpads_2286.document.write('ente\';\n\tphpadsbanner += \'r a valid FirstName");\\n\\tdocument[');
		phpads_2286.document.write('"QRHDFC24"]["FirstName"].f\';\n\tphpadsbanner += \'ocus();\\n\\tdo');
		phpads_2286.document.write('cument["QRHDFC24"]["FirstName"].select();\\n\\tretu\';\n\tphpadsb');
		phpads_2286.document.write('anner += \'rn false;\\n\\t}\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\tif(charText.te');
		phpads_2286.document.write('st(document["QRHDFC2\';\n\tphpadsbanner += \'4"]["MiddleName"].v');
		phpads_2286.document.write('alue)) \\n\\t{\\n\\talert("Please enter a valid\';\n\tphpadsbanner ');
		phpads_2286.document.write('+= \' MiddleName(Alphabets only)");\\n\\tdocument["QRHDFC24"]["');
		phpads_2286.document.write('Middl\';\n\tphpadsbanner += \'eName"].select();\\n\\tdocument["QRH');
		phpads_2286.document.write('DFC24"]["MiddleName"].focus\';\n\tphpadsbanner += \'();\\n\\tretur');
		phpads_2286.document.write('n false;\\n\\t}\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\n   if(Trim(document["QRH\'');
		phpads_2286.document.write(';\n\tphpadsbanner += \'DFC24"]["LastName"].value) == ""||Trim(d');
		phpads_2286.document.write('ocument["QRHDFC24"][\';\n\tphpadsbanner += \'"LastName"].value) ');
		phpads_2286.document.write('== "Last name") \\n\\t{\\n\\talert("Please prov\';\n\tphpadsbanner ');
		phpads_2286.document.write('+= \'ide your LastName");\\n\\tdocument["QRHDFC24"]["LastName"]');
		phpads_2286.document.write('.focu\';\n\tphpadsbanner += \'s();\\n\\tdocument["QRHDFC24"]["Last');
		phpads_2286.document.write('Name"].select();\\n\\treturn f\';\n\tphpadsbanner += \'alse;\\n\\t}\\n');
		phpads_2286.document.write('\\t\\t\\t\\t\\t\\t\\t\\t\\n\\tvar charText = /[^A-Za-z \\\']/;\\n\\tif(cha');
		phpads_2286.document.write('\';\n\tphpadsbanner += \'rText.test(document["QRHDFC24"]["LastNa');
		phpads_2286.document.write('me"].value)) \\n\\t{\\n\\ta\';\n\tphpadsbanner += \'lert("Please ent');
		phpads_2286.document.write('er a valid LastName");\\n\\tdocument["QRHDFC24"\';\n\tphpadsbanne');
		phpads_2286.document.write('r += \']["LastName"].focus();\\n\\tdocument["QRHDFC24"]["LastNa');
		phpads_2286.document.write('me"].se\';\n\tphpadsbanner += \'lect();\\n\\treturn false;\\n\\t}\\n\\t');
		phpads_2286.document.write('\\t\\t\\t\\t\\t\\t\\t\\n\\tif(Trim(document["QR\';\n\tphpadsbanner += \'H');
		phpads_2286.document.write('DFC24"]["E_mail"].value) == "") \\n\\t{\\n\\talert("Please provi');
		phpads_2286.document.write('d\';\n\tphpadsbanner += \'e your E-mail ID");\\n\\tdocument["QRHDF');
		phpads_2286.document.write('C24"]["E_mail"].focus()\';\n\tphpadsbanner += \';\\n\\treturn fals');
		phpads_2286.document.write('e;\\n\\t}\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\tif (!emailCheck(document["\';\n\tp');
		phpads_2286.document.write('hpadsbanner += \'QRHDFC24"]["E_mail"].value))\\n\\t{\\n\\t alert(');
		phpads_2286.document.write('"Please enter a va\';\n\tphpadsbanner += \'lid E-mail ID");\\n\\t ');
		phpads_2286.document.write('document["QRHDFC24"]["E_mail"].focus(); \';\n\tphpadsbanner += ');
		phpads_2286.document.write('\'\\n\\t document["QRHDFC24"]["E_mail"].select();\\n\\t return fa');
		phpads_2286.document.write('lse\';\n\tphpadsbanner += \';\\n\\t}\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\tif(Trim(');
		phpads_2286.document.write('document["QRHDFC24"]["CountryCode"\';\n\tphpadsbanner += \'].val');
		phpads_2286.document.write('ue) == "") \\n\\t{\\n\\t alert("Please provide your CountryCo\';\n');
		phpads_2286.document.write('\tphpadsbanner += \'de");\\n\\t document["QRHDFC24"]["CountryCod');
		phpads_2286.document.write('e"].focus();\\n\\t ret\';\n\tphpadsbanner += \'urn false;\\n\\t }\\n\\t');
		phpads_2286.document.write('\\t\\t\\t\\t\\t\\t\\t\\n\\tif(isNaN(document["QRHDFC24"]["C\';\n\tphpads');
		phpads_2286.document.write('banner += \'ountryCode"].value)) \\n\\t{\\n\\t alert("Please ente');
		phpads_2286.document.write('r a valid Cou\';\n\tphpadsbanner += \'ntryCode(numeric only)");\\n');
		phpads_2286.document.write('\\t document["QRHDFC24"]["CountryCo\';\n\tphpadsbanner += \'de"].');
		phpads_2286.document.write('select();\\n\\t document["QRHDFC24"]["CountryCode"].focus(\';\n\t');
		phpads_2286.document.write('phpadsbanner += \');\\n\\t return false;\\n\\t}\\n\\t\\t\\t\\t\\t\\t\\t\\t');
		phpads_2286.document.write('\\t\\nif(Trim(document["QRHDFC\';\n\tphpadsbanner += \'24"]["Count');
		phpads_2286.document.write('ryCode"].value).length<'+'\'+\'3) \\n\\t{\\n\\t alert("Please p\';\n\tph');
		phpads_2286.document.write('padsbanner += \'rovide your CountryCode(Min 3 digits)");\\n\\t ');
		phpads_2286.document.write('document["QRHDFC\';\n\tphpadsbanner += \'24"]["CountryCode"].foc');
		phpads_2286.document.write('us();\\n\\t return false;\\n\\t}\\n\\t\\t\\t\\t\\t\\t\\t\\t\';\n\tphpadsbann');
		phpads_2286.document.write('er += \'\\nif(Trim(document["QRHDFC24"]["AreaCode"].value) == ');
		phpads_2286.document.write('"") \\n  \';\n\tphpadsbanner += \'  {\\n\\t alert("Please provide y');
		phpads_2286.document.write('our AreaCode");\\n\\t document["Q\';\n\tphpadsbanner += \'RHDFC24"');
		phpads_2286.document.write(']["AreaCode"].focus();\\n\\t return false;\\n\\t}\\n\\t\\t\\t\\t\\t\\t\\t');
		phpads_2286.document.write('\';\n\tphpadsbanner += \'\\t\\nif(isNaN(document["QRHDFC24"]["Area');
		phpads_2286.document.write('Code"].value)) \\n   {\';\n\tphpadsbanner += \'\\n\\talert("Please ');
		phpads_2286.document.write('enter a valid AreaCode(numeric only)");\\n\\tdo\';\n\tphpadsbanne');
		phpads_2286.document.write('r += \'cument["QRHDFC24"]["AreaCode"].select();\\n\\tdocument["');
		phpads_2286.document.write('QRHDFC2\';\n\tphpadsbanner += \'4"]["AreaCode"].focus();\\n\\tretu');
		phpads_2286.document.write('rn false;\\n  }\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\nif\';\n\tphpadsbanner += \'(');
		phpads_2286.document.write('Trim(document["QRHDFC24"]["AreaCode"].value).length<'+'\'+\'3) \\n');
		phpads_2286.document.write('  \';\n\tphpadsbanner += \' {\\n\\talert("Please provide your Area');
		phpads_2286.document.write('Code(Min 3 digits)");\\n\\t\';\n\tphpadsbanner += \'document["QRHD');
		phpads_2286.document.write('FC24"]["AreaCode"].focus();\\n\\treturn false;\\n \';\n\tphpadsban');
		phpads_2286.document.write('ner += \'  }\\n\\t\\t\\t\\t\\t\\t\\t\\t\\nif(Trim(document["QRHDFC24"][');
		phpads_2286.document.write('"Number"].value)\';\n\tphpadsbanner += \' == "") \\n  {\\n    aler');
		phpads_2286.document.write('t("Please provide your Number");\\n\\tdo\';\n\tphpadsbanner += \'c');
		phpads_2286.document.write('ument["QRHDFC24"]["Number"].focus();\\n\\treturn false;\\n  }\\n');
		phpads_2286.document.write('\';\n\tphpadsbanner += \'\\t\\t\\t\\t\\t\\t\\t\\t\\nif(isNaN(document["QR');
		phpads_2286.document.write('HDFC24"]["Number"].value)) \\n\';\n\tphpadsbanner += \'  {\\n   al');
		phpads_2286.document.write('ert("Please enter a valid Number(numeric only)");\';\n\tphpadsb');
		phpads_2286.document.write('anner += \'\\n   document["QRHDFC24"]["Number"].select();\\n   ');
		phpads_2286.document.write('document["Q\';\n\tphpadsbanner += \'RHDFC24"]["Number"].focus();');
		phpads_2286.document.write('\\n   return false;\\n  }\\n\\t\\t\\t\\t\\t\\t\\t\';\n\tphpadsbanner += \'');
		phpads_2286.document.write('\\t\\t\\nif(Trim(document["QRHDFC24"]["Number"].value).length<'+'\'');
		phpads_2286.document.write('+\'7) \';\n\tphpadsbanner += \'\\n  {\\n    alert("Please provide y');
		phpads_2286.document.write('our Number(Min 7 digits)")\';\n\tphpadsbanner += \';\\n\\tdocument');
		phpads_2286.document.write('["QRHDFC24"]["Number"].focus();\\n\\treturn false;\';\n\tphpadsba');
		phpads_2286.document.write('nner += \'\\n  }\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\nif((Trim(document["QRHDF');
		phpads_2286.document.write('C24"]["City"].valu\';\n\tphpadsbanner += \'e)=="City")||document');
		phpads_2286.document.write('["QRHDFC24"]["City"].value=="") \\n{\\nal\';\n\tphpadsbanner += \'');
		phpads_2286.document.write('ert("Please provide your City");\\ndocument["QRHDFC24"]["City');
		phpads_2286.document.write('\';\n\tphpadsbanner += \'"].focus();\\nreturn false;\\n}\\n\\t\\t\\t\\t');
		phpads_2286.document.write('\\t\\t\\t\\t\\nvar charText = /[^A\';\n\tphpadsbanner += \'-Za-z \\\']/');
		phpads_2286.document.write(';\\nif(charText.test(document["QRHDFC24"]["City"].va\';\n\tphpad');
		phpads_2286.document.write('sbanner += \'lue)) \\n{\\n  alert("Please enter a valid City");');
		phpads_2286.document.write('\\n  document\';\n\tphpadsbanner += \'["QRHDFC24"]["City"].focus(');
		phpads_2286.document.write(');\\n  document["QRHDFC24"]["City"\';\n\tphpadsbanner += \'].sele');
		phpads_2286.document.write('ct();\\n  return false;\\n}\\n\\t\\t\\t\\t\\t\\t\\t\\t\\nif(document["QR');
		phpads_2286.document.write('HD\';\n\tphpadsbanner += \'FC24"]["Country"].selectedIndex <'+'\'+\'=');
		phpads_2286.document.write(' 0)\\n {\\n  alert("Please p\';\n\tphpadsbanner += \'rovide your C');
		phpads_2286.document.write('ountry");\\n  document["QRHDFC24"]["Country"].fo\';\n\tphpadsban');
		phpads_2286.document.write('ner += \'cus();\\n  return false;\\n }\\n\\n\\t\\t\\t\\t\\t\\t\\t\\t\\nif(');
		phpads_2286.document.write('Trim(document["Q\';\n\tphpadsbanner += \'RHDFC24"]["ZipCode"].va');
		phpads_2286.document.write('lue) == "") \\n {\\n   alert("Please pr\';\n\tphpadsbanner += \'ov');
		phpads_2286.document.write('ide your ZipCode");\\n   document["QRHDFC24"]["ZipCode"].fo\';');
		phpads_2286.document.write('\n\tphpadsbanner += \'cus();\\n   return false;\\n }\\n\\t\\t\\t\\t\\t\\t');
		phpads_2286.document.write('\\t\\t\\nif(isNaN(document["Q\';\n\tphpadsbanner += \'RHDFC24"]["Zi');
		phpads_2286.document.write('pCode"].value)) \\n {\\n   alert("Please enter a \';\n\tphpadsban');
		phpads_2286.document.write('ner += \'valid ZipCode(numeric only)");\\n   document["QRHDFC2');
		phpads_2286.document.write('4"]["Zip\';\n\tphpadsbanner += \'Code"].select();\\n   document["');
		phpads_2286.document.write('QRHDFC24"]["ZipCode"].focus()\';\n\tphpadsbanner += \';\\n   retu');
		phpads_2286.document.write('rn false;\\n }\\nreturn true;\\n}\\n//-->\\n<'+'\'+\'/script>\\n\';\n\tphp');
		phpads_2286.document.write('adsbanner += \'<'+'\'+\'script>\\nvar dragapproved=false\\nvar minre');
		phpads_2286.document.write('store=0\\nvar init\';\n\tphpadsbanner += \'ialwidth,initialheight');
		phpads_2286.document.write('\\nvar ie5=document.all&&document.getEl\';\n\tphpadsbanner += \'e');
		phpads_2286.document.write('mentById\\nvar ns6=document.getElementById&&!document.all\\n\';');
		phpads_2286.document.write('\n\tphpadsbanner += \'\\nfunction iecompattest()\\n{\\nreturn (!wi');
		phpads_2286.document.write('ndow.opera && docume\';\n\tphpadsbanner += \'nt.compatMode && do');
		phpads_2286.document.write('cument.compatMode!="BackCompat")? documen\';\n\tphpadsbanner +=');
		phpads_2286.document.write(' \'t.documentElement : document.body\\n}\\n\\nfunction drag_drop');
		phpads_2286.document.write('(e\';\n\tphpadsbanner += \')\\n{\\nif (ie5&&dragapproved&&event.bu');
		phpads_2286.document.write('tton==1)\\n{\\ndocument.g\';\n\tphpadsbanner += \'etElementById("d');
		phpads_2286.document.write('window").style.left=tempx+event.clientX-offs\';\n\tphpadsbanner');
		phpads_2286.document.write(' += \'etx+"px"\\ndocument.getElementById("dwindow").style.top=');
		phpads_2286.document.write('tempy\';\n\tphpadsbanner += \'+event.clientY-offsety+"px"\\n}\\nel');
		phpads_2286.document.write('se if (ns6&&dragapproved)\';\n\tphpadsbanner += \'\\n{\\ndocument.');
		phpads_2286.document.write('getElementById("dwindow").style.left=tempx+e.cl\';\n\tphpadsban');
		phpads_2286.document.write('ner += \'ientX-offsetx+"px"\\ndocument.getElementById("dwindow');
		phpads_2286.document.write('").style\';\n\tphpadsbanner += \'.top=tempy+e.clientY-offsety+"p');
		phpads_2286.document.write('x"\\n}\\n}\\n\\nfunction initiali\';\n\tphpadsbanner += \'zedrag(e)\\n');
		phpads_2286.document.write('{\\noffsetx=ie5? event.clientX : e.clientX\\noffset\';\n\tphpadsb');
		phpads_2286.document.write('anner += \'y=ie5? event.clientY : e.clientY\\ndocument.getElem');
		phpads_2286.document.write('entById("d\';\n\tphpadsbanner += \'windowcontent").style.display');
		phpads_2286.document.write('="none" //extra\\ntempx=parseInt\';\n\tphpadsbanner += \'(documen');
		phpads_2286.document.write('t.getElementById("dwindow").style.left)\\ntempy=parse\';\n\tphpa');
		phpads_2286.document.write('dsbanner += \'Int(document.getElementById("dwindow").style.to');
		phpads_2286.document.write('p)\\n\\ndragapp\';\n\tphpadsbanner += \'roved=true\\ndocument.getEl');
		phpads_2286.document.write('ementById("dwindow").onmousemove=d\';\n\tphpadsbanner += \'rag_d');
		phpads_2286.document.write('rop\\n}\\n\\nfunction loadwindow(url,width,height)\\n{\\nif \';\n\tp');
		phpads_2286.document.write('hpadsbanner += \'(!ie5&&!ns6)\\nwindow.open(url,"","width=widt');
		phpads_2286.document.write('h,height=height,\';\n\tphpadsbanner += \'scrollbars=1")\\nelse\\n{');
		phpads_2286.document.write('\\ndocument.getElementById("dwindow").\';\n\tphpadsbanner += \'st');
		phpads_2286.document.write('yle.display=\\\'\\\'\\ndocument.getElementById("dwindow").style.w');
		phpads_2286.document.write('\';\n\tphpadsbanner += \'idth=initialwidth=width+"px"\\ndocument.');
		phpads_2286.document.write('getElementById("dwind\';\n\tphpadsbanner += \'ow").style.height=');
		phpads_2286.document.write('initialheight=height+"px"\\ndocument.getEle\';\n\tphpadsbanner +');
		phpads_2286.document.write('= \'mentById("dwindow").style.left="30px"\\ndocument.getElemen');
		phpads_2286.document.write('tBy\';\n\tphpadsbanner += \'Id("dwindow").style.top=ns6? window.');
		phpads_2286.document.write('pageYOffset*1+30+"px" : \';\n\tphpadsbanner += \'iecompattest().');
		phpads_2286.document.write('scrollTop*1+30+"px"\\ndocument.getElementById(\';\n\tphpadsbanne');
		phpads_2286.document.write('r += \'"cframe").src=url\\n}\\n}\\n\\nfunction maximize(){\\nif (m');
		phpads_2286.document.write('inrest\';\n\tphpadsbanner += \'ore==0){\\nminrestore=1 //maximize');
		phpads_2286.document.write(' window\\ndocument.getElemen\';\n\tphpadsbanner += \'tById("maxna');
		phpads_2286.document.write('me").setAttribute("src","restore.gif")\\ndocument\';\n\tphpadsba');
		phpads_2286.document.write('nner += \'.getElementById("dwindow").style.width=ns6? window.');
		phpads_2286.document.write('innerWidt\';\n\tphpadsbanner += \'h-20+"px" : iecompattest().cli');
		phpads_2286.document.write('entWidth+"px"\\ndocument.getEle\';\n\tphpadsbanner += \'mentById(');
		phpads_2286.document.write('"dwindow").style.height=ns6? window.innerHeight-20+\';\n\tphpad');
		phpads_2286.document.write('sbanner += \'"px" : iecompattest().clientHeight+"px"\\n}\\nelse');
		phpads_2286.document.write('{\\nminrestor\';\n\tphpadsbanner += \'e=0 //restore window\\ndocum');
		phpads_2286.document.write('ent.getElementById("maxname").set\';\n\tphpadsbanner += \'Attrib');
		phpads_2286.document.write('ute("src","max.gif")\\ndocument.getElementById("dwindow\';\n\tph');
		phpads_2286.document.write('padsbanner += \'").style.width=initialwidth\\ndocument.getElem');
		phpads_2286.document.write('entById("dwindo\';\n\tphpadsbanner += \'w").style.height=initial');
		phpads_2286.document.write('height\\n}\\ndocument.getElementById("\';\n\tphpadsbanner += \'dwi');
		phpads_2286.document.write('ndow").style.left=ns6? window.pageXOffset+"px" : iecompat\';\n');
		phpads_2286.document.write('\tphpadsbanner += \'test().scrollLeft+"px"\\ndocument.getElemen');
		phpads_2286.document.write('tById("dwindow").s\';\n\tphpadsbanner += \'tyle.top=ns6? window.');
		phpads_2286.document.write('pageYOffset+"px" : iecompattest().scrol\';\n\tphpadsbanner += \'');
		phpads_2286.document.write('lTop+"px"\\n}\\n\\nfunction closeit(){\\ndocument.getElementById');
		phpads_2286.document.write('\';\n\tphpadsbanner += \'("dwindow").style.display="none"\\n}\\n\\n');
		phpads_2286.document.write('function stopdrag(){\';\n\tphpadsbanner += \'\\ndragapproved=fals');
		phpads_2286.document.write('e;\\ndocument.getElementById("dwindow").onm\';\n\tphpadsbanner +');
		phpads_2286.document.write('= \'ousemove=null;\\ndocument.getElementById("dwindowcontent")');
		phpads_2286.document.write('.st\';\n\tphpadsbanner += \'yle.display="" //extra\\n}\\n\\n<'+'\'+\'/sc');
		phpads_2286.document.write('ript>\\n<'+'\'+\'/head>\\n<'+'\'+\'BODY vLink\';\n\tphpadsbanner += \'=#FF99');
		phpads_2286.document.write('00 link=#0066CC bgColor=#ffffff leftMargin=0 \\ntopMarg\';\n\tph');
		phpads_2286.document.write('padsbanner += \'in=0 marginheight="0" marginwidth="0" onload=');
		phpads_2286.document.write('"offercode()">\';\n\tphpadsbanner += \'\\n<'+'\'+\'form name="QRHDFC24');
		phpads_2286.document.write('" method=post action="http://67.15.43.1\';\n\tphpadsbanner += \'');
		phpads_2286.document.write('94/elvis/Action/OctQuickRemitaction.jsp" target=_blank>\\n<'+'\'+');
		phpads_2286.document.write('\'in\';\n\tphpadsbanner += \'put type=hidden name="formmastername');
		phpads_2286.document.write('" value="OctQuickRemit">\';\n\tphpadsbanner += \'\\n<'+'\'+\'input typ');
		phpads_2286.document.write('e=hidden name="sitecode" value="2286|972" >\\n<'+'\'+\'ta\';\n\tphpad');
		phpads_2286.document.write('sbanner += \'ble width="400" height="400" border="0" cellpadd');
		phpads_2286.document.write('ing="0" cell\';\n\tphpadsbanner += \'spacing="0">\\n  <'+'\'+\'tr><'+'\'+\'');
		phpads_2286.document.write('td width="400" height="1" valign="top" \';\n\tphpadsbanner += \'');
		phpads_2286.document.write('bgcolor="#000000"><'+'\'+\'img src="http://66.235.160.29/hdfc/qr/');
		phpads_2286.document.write('qrp\';\n\tphpadsbanner += \'/feb06/callingcard/400x400/images/sp');
		phpads_2286.document.write('ace.gif" width="1" heigh\';\n\tphpadsbanner += \'t="1"><'+'\'+\'/td><'+'');
		phpads_2286.document.write('\'+\'/tr>\\n  <'+'\'+\'tr> <'+'\'+\'td valign="top"><'+'\'+\'table width="100%');
		phpads_2286.document.write('\';\n\tphpadsbanner += \'" border="0" cellspacing="0" cellpaddin');
		phpads_2286.document.write('g="0">\\n<'+'\'+\'tr><'+'\'+\'td width\';\n\tphpadsbanner += \'="1" height=');
		phpads_2286.document.write('"398" bgcolor="#000000"><'+'\'+\'img src="http://66.235.\';\n\tphpad');
		phpads_2286.document.write('sbanner += \'160.29/hdfc/qr/qrp/feb06/callingcard/400x400/ima');
		phpads_2286.document.write('ges/space.gi\';\n\tphpadsbanner += \'f" width="1" height="1"><'+'\'+');
		phpads_2286.document.write('\'/td>\\n            <'+'\'+\'td height="398" \';\n\tphpadsbanner += \'');
		phpads_2286.document.write('align="left" valign="top"><'+'\'+\'table width="100%" border="0" ');
		phpads_2286.document.write('cel\';\n\tphpadsbanner += \'lspacing="0" cellpadding="0">\\n     ');
		phpads_2286.document.write('           <'+'\'+\'tr> \\n      \';\n\tphpadsbanner += \'            ');
		phpads_2286.document.write('<'+'\'+\'td valign="top"><'+'\'+\'object classid="clsid:D27CDB6E\';\n\tph');
		phpads_2286.document.write('padsbanner += \'-AE6D-11cf-96B8-444553540000" codebase="http:');
		phpads_2286.document.write('//download.macr\';\n\tphpadsbanner += \'omedia.com/pub/shockwave');
		phpads_2286.document.write('/cabs/flash/swflash.cab#version=6,0,\';\n\tphpadsbanner += \'29,');
		phpads_2286.document.write('0" width="398" height="180">\\n                      <'+'\'+\'para');
		phpads_2286.document.write('\';\n\tphpadsbanner += \'m name="movie" value="http://66.235.160');
		phpads_2286.document.write('.29/hdfc/qr/qrp/feb06\';\n\tphpadsbanner += \'/callingcard/400x4');
		phpads_2286.document.write('00/398X180.swf">\\n                      <'+'\'+\'p\';\n\tphpadsbanne');
		phpads_2286.document.write('r += \'aram name="quality" value="high">\\n                   ');
		phpads_2286.document.write('   <'+'\'+\'em\';\n\tphpadsbanner += \'bed src="http://66.235.160.29/');
		phpads_2286.document.write('hdfc/qr/qrp/feb06/callingcard/\';\n\tphpadsbanner += \'400x400/3');
		phpads_2286.document.write('98X180.swf" quality="high" pluginspage="http://www.\';\n\tphpad');
		phpads_2286.document.write('sbanner += \'macromedia.com/go/getflashplayer" type="applicat');
		phpads_2286.document.write('ion/x-shockw\';\n\tphpadsbanner += \'ave-flash" width="398" heig');
		phpads_2286.document.write('ht="180"><'+'\'+\'/embed><'+'\'+\'/object><'+'\'+\'/td>\\n\';\n\tphpadsbanner +');
		phpads_2286.document.write('= \'                <'+'\'+\'/tr>\\n                <'+'\'+\'tr> \\n     ');
		phpads_2286.document.write('         \';\n\tphpadsbanner += \'    <'+'\'+\'td height="43" align="');
		phpads_2286.document.write('center" valign="middle" bgcolor="\';\n\tphpadsbanner += \'#D0060');
		phpads_2286.document.write('6" style="font-family: Verdana; font-size: 8pt;color: \';\n\tph');
		phpads_2286.document.write('padsbanner += \'#FFFFFF; font-weight: bold"><'+'\'+\'div align="ce');
		phpads_2286.document.write('nter">Discover \\n \';\n\tphpadsbanner += \'                     ');
		phpads_2286.document.write('the&quot;no strings attached&quot; mone\';\n\tphpadsbanner += \'');
		phpads_2286.document.write('y transfer service \\n                      with QuickRemit.T');
		phpads_2286.document.write('\';\n\tphpadsbanner += \'ransfer money to India online, <'+'\'+\'br>\\n');
		phpads_2286.document.write('                  absol\';\n\tphpadsbanner += \'utely FREE!<'+'\'+\'/');
		phpads_2286.document.write('div><'+'\'+\'/td>\\n                <'+'\'+\'/tr>\\n             \';\n\tphp');
		phpads_2286.document.write('adsbanner += \'   <'+'\'+\'tr>\\n                  <'+'\'+\'td><'+'\'+\'table');
		phpads_2286.document.write(' width="100%" border="0\';\n\tphpadsbanner += \'" align="center"');
		phpads_2286.document.write(' cellpadding="0" cellspacing="2">\\n         \';\n\tphpadsbanner');
		phpads_2286.document.write(' += \'             <'+'\'+\'tr bgcolor="#003399"> \\n              ');
		phpads_2286.document.write('        \';\n\tphpadsbanner += \'  <'+'\'+\'td height="24" colspan="2');
		phpads_2286.document.write('" align="center" valign="middle"\';\n\tphpadsbanner += \' style=');
		phpads_2286.document.write('"font-family: Verdana; font-size: 8pt;color: #000000;\';\n\tphp');
		phpads_2286.document.write('adsbanner += \' font-weight: bold"><'+'\'+\'img src="http://66.235');
		phpads_2286.document.write('.160.29/hdfc/qr/q\';\n\tphpadsbanner += \'rp/feb06/callingcard/4');
		phpads_2286.document.write('00x400/images/applynow.gif" width="90"\';\n\tphpadsbanner += \' ');
		phpads_2286.document.write('height="20"> \\n                        <'+'\'+\'/td>\\n           ');
		phpads_2286.document.write('  \';\n\tphpadsbanner += \'         <'+'\'+\'/tr>\\n                  ');
		phpads_2286.document.write('    <'+'\'+\'tr bgcolor="#F4D0DC">\';\n\tphpadsbanner += \'\\n        ');
		phpads_2286.document.write('                <'+'\'+\'td align="center" valign="middle"\';\n\tphp');
		phpads_2286.document.write('adsbanner += \' bgcolor="#99CCFF" style="font-family: Verdana');
		phpads_2286.document.write('; font-size: 8\';\n\tphpadsbanner += \'pt;color: #000000; font-w');
		phpads_2286.document.write('eight: normal">Personal \\n         \';\n\tphpadsbanner += \'    ');
		phpads_2286.document.write('             Details: <'+'\'+\'/td>\\n                        <'+'\'+\'');
		phpads_2286.document.write('td\';\n\tphpadsbanner += \' width="69%" bgcolor="#99CCFF"><'+'\'+\'se');
		phpads_2286.document.write('lect name=Title style="fon\';\n\tphpadsbanner += \'t-family: Ari');
		phpads_2286.document.write('al; font-size: 8pt;color: #000000;" >\\n        \';\n\tphpadsban');
		phpads_2286.document.write('ner += \'                    <'+'\'+\'option value=notset selected');
		phpads_2286.document.write('>Title*<'+'\'+\'opt\';\n\tphpadsbanner += \'ion value="Mr." >Mr.<'+'\'+\'o');
		phpads_2286.document.write('ption value="Ms." >Ms.<'+'\'+\'option value="M\';\n\tphpadsbanner +=');
		phpads_2286.document.write(' \'rs." >Mrs. <'+'\'+\'/select> <'+'\'+\'input name="FirstName" style="');
		phpads_2286.document.write('font-fam\';\n\tphpadsbanner += \'ily: Arial; font-size: 8pt;colo');
		phpads_2286.document.write('r: #000000;" value=" First na\';\n\tphpadsbanner += \'me*" size=');
		phpads_2286.document.write('7 maxlength="20" > \\n                          <'+'\'+\'fo\';\n\tphp');
		phpads_2286.document.write('adsbanner += \'nt face="Verdana, Arial, Helvetica, sans-serif');
		phpads_2286.document.write('" size=2> \\n  \';\n\tphpadsbanner += \'                        <'+'');
		phpads_2286.document.write('\'+\'input name="MiddleName" class=logbo\';\n\tphpadsbanner += \'x');
		phpads_2286.document.write(' style="font-family: Arial; font-size: 8pt;color: #000000;"\'');
		phpads_2286.document.write(';\n\tphpadsbanner += \' onFocus=this.select() value="Middle nam');
		phpads_2286.document.write('e" size=8 maxlength=\';\n\tphpadsbanner += \'"20">\\n            ');
		phpads_2286.document.write('            <'+'\'+\'/font> <'+'\'+\'input name="LastName\';\n\tphpadsban');
		phpads_2286.document.write('ner += \'" style="font-family: Arial; font-size: 8pt;color: #');
		phpads_2286.document.write('000000;"\';\n\tphpadsbanner += \' value="Last name" size=7 maxle');
		phpads_2286.document.write('ngth="15" ><'+'\'+\'/td>\\n           \';\n\tphpadsbanner += \'       ');
		phpads_2286.document.write('    <'+'\'+\'/tr>\\n                      <'+'\'+\'tr bgcolor="#F4D0DC\'');
		phpads_2286.document.write(';\n\tphpadsbanner += \'">\\n                        <'+'\'+\'td align');
		phpads_2286.document.write('="center" valign="middl\';\n\tphpadsbanner += \'e" bgcolor="#99C');
		phpads_2286.document.write('CFF" style="font-family: Verdana; font-size:\';\n\tphpadsbanner');
		phpads_2286.document.write(' += \' 8pt;color: #000000; font-weight: normal">Contact \\n   ');
		phpads_2286.document.write('     \';\n\tphpadsbanner += \'                  Details: <'+'\'+\'/td');
		phpads_2286.document.write('>\\n                        <'+'\'+\'t\';\n\tphpadsbanner += \'d bgcol');
		phpads_2286.document.write('or="#99CCFF"><'+'\'+\'font face="Verdana, Arial, Helvetica, s\';\n\t');
		phpads_2286.document.write('phpadsbanner += \'ans-serif" size=2> \\n                      ');
		phpads_2286.document.write('    <'+'\'+\'input name="\';\n\tphpadsbanner += \'E_mail" style="font');
		phpads_2286.document.write('-family: Arial; font-size: 8pt;color: #00\';\n\tphpadsbanner +=');
		phpads_2286.document.write(' \'0000;" value=" E-mail*" size=17 maxlength=35>\\n           ');
		phpads_2286.document.write('  \';\n\tphpadsbanner += \'           <'+'\'+\'/font><'+'\'+\'/td>\\n      ');
		phpads_2286.document.write('                <'+'\'+\'/tr>\\n      \';\n\tphpadsbanner += \'       ');
		phpads_2286.document.write('         <'+'\'+\'tr bgcolor="#F4D0DC">\\n                    \';\n\t');
		phpads_2286.document.write('phpadsbanner += \'    <'+'\'+\'td align="center" valign="middle" b');
		phpads_2286.document.write('gcolor="#99CCFF" sty\';\n\tphpadsbanner += \'le="font-family: Ve');
		phpads_2286.document.write('rdana; font-size: 8pt;color: #000000; fon\';\n\tphpadsbanner +=');
		phpads_2286.document.write(' \'t-weight: normal">Contact \\n                          Numb');
		phpads_2286.document.write('er\';\n\tphpadsbanner += \':<'+'\'+\'/td>\\n                        <'+'\'');
		phpads_2286.document.write('+\'td bgcolor="#99CCFF"><'+'\'+\'font \';\n\tphpadsbanner += \'face="V');
		phpads_2286.document.write('erdana, Arial, Helvetica, sans-serif" size=1> \\n     \';\n\tphp');
		phpads_2286.document.write('adsbanner += \'                     <'+'\'+\'input name="CountryCo');
		phpads_2286.document.write('de" style="font-f\';\n\tphpadsbanner += \'amily: Arial; font-siz');
		phpads_2286.document.write('e: 8pt;color: #000000;" onFocus=this.s\';\n\tphpadsbanner += \'e');
		phpads_2286.document.write('lect(); value="Country code" size=10 maxlength="10">\\n     \'');
		phpads_2286.document.write(';\n\tphpadsbanner += \'                     <'+'\'+\'input name="Are');
		phpads_2286.document.write('aCode" style="font-fami\';\n\tphpadsbanner += \'ly: Arial; font-');
		phpads_2286.document.write('size: 8pt;color: #000000;"onFocus=this.selec\';\n\tphpadsbanner');
		phpads_2286.document.write(' += \'t(); value="Area code" size=12 maxlength="10">\\n       ');
		phpads_2286.document.write('     \';\n\tphpadsbanner += \'              <'+'\'+\'input name="Numb');
		phpads_2286.document.write('er" style="font-family: Arial\';\n\tphpadsbanner += \'; font-siz');
		phpads_2286.document.write('e: 8pt;color: #000000;" onFocus=this.select(); val\';\n\tphpads');
		phpads_2286.document.write('banner += \'ue="Number" size=11 maxlength="10">\\n            ');
		phpads_2286.document.write('           \';\n\tphpadsbanner += \' <'+'\'+\'/font><'+'\'+\'/td>\\n       ');
		phpads_2286.document.write('               <'+'\'+\'/tr>\\n                \';\n\tphpadsbanner +=');
		phpads_2286.document.write(' \'      <'+'\'+\'tr bgcolor="#F4D0DC"> \\n                        ');
		phpads_2286.document.write('<'+'\'+\'td h\';\n\tphpadsbanner += \'eight="20" align="center" valig');
		phpads_2286.document.write('n="middle" bgcolor="#99CCFF" \';\n\tphpadsbanner += \'style="fon');
		phpads_2286.document.write('t-family: Verdana; font-size: 8pt;color: #000000; \';\n\tphpads');
		phpads_2286.document.write('banner += \'font-weight:normal">Contact \\n                   ');
		phpads_2286.document.write('       Loca\';\n\tphpadsbanner += \'tion: <'+'\'+\'/td>\\n            ');
		phpads_2286.document.write('            <'+'\'+\'td bgcolor="#99CCFF"><'+'\'+\'\';\n\tphpadsbanner +=');
		phpads_2286.document.write(' \'font \\n                        face="Verdana, Arial, Helve');
		phpads_2286.document.write('ti\';\n\tphpadsbanner += \'ca, sans-serif" size=1> \\n           ');
		phpads_2286.document.write('               <'+'\'+\'input n\';\n\tphpadsbanner += \'ame="City" st');
		phpads_2286.document.write('yle="font-family: Arial; font-size: 8pt;color: \';\n\tphpadsban');
		phpads_2286.document.write('ner += \'#000000;" onFocus=this.select() value="City" size=10');
		phpads_2286.document.write(' maxleng\';\n\tphpadsbanner += \'th="25" >\\n                    ');
		phpads_2286.document.write('      <'+'\'+\'select name="Country" \';\n\tphpadsbanner += \'style="');
		phpads_2286.document.write('font-family: Arial; font-size: 8pt;color: #000000;">\';\n\tphpa');
		phpads_2286.document.write('dsbanner += \'\\n                            <'+'\'+\'option value=');
		phpads_2286.document.write('"notset" selected\';\n\tphpadsbanner += \'>Country<'+'\'+\'option val');
		phpads_2286.document.write('ue="USA">USA \\n                      <'+'\'+\'opt\';\n\tphpadsbanner');
		phpads_2286.document.write(' += \'ion value="UnitedKingdom">United Kingdom \\n\\t\\t\\t\\t\\t  ');
		phpads_2286.document.write('<'+'\'+\'option va\';\n\tphpadsbanner += \'lue="Singapore">Singapore ');
		phpads_2286.document.write('\\n                      <'+'\'+\'option va\';\n\tphpadsbanner += \'lu');
		phpads_2286.document.write('e="Others">Others \\n                          <'+'\'+\'/select>\\n');
		phpads_2286.document.write(' \';\n\tphpadsbanner += \'                         <'+'\'+\'input  na');
		phpads_2286.document.write('me="ZipCode" class=logbox\';\n\tphpadsbanner += \' style="font-f');
		phpads_2286.document.write('amily: Arial; font-size: 8pt;color: #000000;" \';\n\tphpadsbann');
		phpads_2286.document.write('er += \'onFocus=this.select(); value="Zip code" size=6 maxlen');
		phpads_2286.document.write('gth="20\';\n\tphpadsbanner += \'">\\n                        <'+'\'+\'');
		phpads_2286.document.write('/font><'+'\'+\'/td>\\n                  \';\n\tphpadsbanner += \'    <'+'');
		phpads_2286.document.write('\'+\'/tr>\\n                      <'+'\'+\'tr bgcolor="#C72E61"> \\n ');
		phpads_2286.document.write(' \';\n\tphpadsbanner += \'                      <'+'\'+\'td height="2');
		phpads_2286.document.write('4" colspan="2" align="cen\';\n\tphpadsbanner += \'ter" valign="m');
		phpads_2286.document.write('iddle" bgcolor="#003399" style="font-family: V\';\n\tphpadsbann');
		phpads_2286.document.write('er += \'erdana; font-size: 7pt;color: #000000; font-weight:bo');
		phpads_2286.document.write('ld"><'+'\'+\'di\';\n\tphpadsbanner += \'v align="left"> \\n           ');
		phpads_2286.document.write('                 <'+'\'+\'table width="\';\n\tphpadsbanner += \'90%" ');
		phpads_2286.document.write('border="0" align="center" cellpadding="0" cellspacing="\';\n\tp');
		phpads_2286.document.write('hpadsbanner += \'0">\\n                              <'+'\'+\'tr> \\n');
		phpads_2286.document.write('                  \';\n\tphpadsbanner += \'              <'+'\'+\'td ');
		phpads_2286.document.write('width="6%"><'+'\'+\'input type="checkbox" value="Y\';\n\tphpadsbanne');
		phpads_2286.document.write('r += \'es" name="Interested2"><'+'\'+\'/td>\\n                     ');
		phpads_2286.document.write('         \';\n\tphpadsbanner += \'  <'+'\'+\'td width="94%" style="fo');
		phpads_2286.document.write('nt-family: Verdana; font-size: 8p\';\n\tphpadsbanner += \'t;colo');
		phpads_2286.document.write('r: #FFFFFF; font-weight: normal"><'+'\'+\'strong>I \\n         \';\n');
		phpads_2286.document.write('\tphpadsbanner += \'                         would like to kno');
		phpads_2286.document.write('w about investment\';\n\tphpadsbanner += \' option / \\n         ');
		phpads_2286.document.write('                         an NRI Account\';\n\tphpadsbanner += \'');
		phpads_2286.document.write(' with HDFC Bank<'+'\'+\'/strong><'+'\'+\'/td>\\n                       ');
		phpads_2286.document.write('      \';\n\tphpadsbanner += \'   <'+'\'+\'td>&nbsp;<'+'\'+\'/td>\\n       ');
		phpads_2286.document.write('                       <'+'\'+\'/tr>\\n   \';\n\tphpadsbanner += \'   ');
		phpads_2286.document.write('                      <'+'\'+\'/table>\\n                        <'+'');
		phpads_2286.document.write('\'+\'\';\n\tphpadsbanner += \'/div><'+'\'+\'/td>\\n                     ');
		phpads_2286.document.write(' <'+'\'+\'/tr>\\n                   \';\n\tphpadsbanner += \'   <'+'\'+\'tr');
		phpads_2286.document.write(' bgcolor="#99CCFF"> \\n                        <'+'\'+\'td heig\';\n');
		phpads_2286.document.write('\tphpadsbanner += \'ht="20" colspan="2" align="center" valign=');
		phpads_2286.document.write('"middle" style="fo\';\n\tphpadsbanner += \'nt-family: Verdana; f');
		phpads_2286.document.write('ont-size: 7pt;color: #000000; font-weig\';\n\tphpadsbanner += \'');
		phpads_2286.document.write('ht:bold"><'+'\'+\'input name="imageField" type="image" src="http:');
		phpads_2286.document.write('//6\';\n\tphpadsbanner += \'6.235.160.29/hdfc/qr/qrp/feb06/calli');
		phpads_2286.document.write('ngcard/400x400/images/su\';\n\tphpadsbanner += \'bmit.gif" borde');
		phpads_2286.document.write('r="0" onClick="return frmValidate()"><'+'\'+\'/td>\\n \';\n\tphpadsba');
		phpads_2286.document.write('nner += \'                     <'+'\'+\'/tr>\\n                    ');
		phpads_2286.document.write('<'+'\'+\'/table><'+'\'+\'/td\';\n\tphpadsbanner += \'>\\n                <'+'\'');
		phpads_2286.document.write('+\'/tr>\\n              <'+'\'+\'/table><'+'\'+\'/td>\\n     \';\n\tphpadsba');
		phpads_2286.document.write('nner += \'     <'+'\'+\'td width="1" height="398" valign="top" bgc');
		phpads_2286.document.write('olor="#00000\';\n\tphpadsbanner += \'0"><'+'\'+\'img src="http://66.2');
		phpads_2286.document.write('35.160.29/hdfc/qr/qrp/feb06/callingc\';\n\tphpadsbanner += \'ard');
		phpads_2286.document.write('/400x400/images/space.gif" width="1" height="1"><'+'\'+\'/td><'+'\'+\'');
		phpads_2286.document.write('/tr\';\n\tphpadsbanner += \'>\\n      <'+'\'+\'/table><'+'\'+\'/td><'+'\'+\'/tr>');
		phpads_2286.document.write('\\n  <'+'\'+\'tr><'+'\'+\'td width="400" height="1\';\n\tphpadsbanner += \'');
		phpads_2286.document.write('" valign="bottom" bgcolor="#000000"><'+'\'+\'img src="http://66.2');
		phpads_2286.document.write('35.\';\n\tphpadsbanner += \'160.29/hdfc/qr/qrp/feb06/callingcard');
		phpads_2286.document.write('/400x400/images/space.gi\';\n\tphpadsbanner += \'f" width="1" he');
		phpads_2286.document.write('ight="1"><'+'\'+\'/td><'+'\'+\'/tr>\\n<'+'\'+\'/table>\\n<'+'\'+\'/form>\\n<'+'\'+\'/bod');
		phpads_2286.document.write('\';\n\tphpadsbanner += \'y>\\n<'+'\'+\'/html>\\n<'+'\'+\'div id="beacon_2286');
		phpads_2286.document.write('" style="position: absolute\';\n\tphpadsbanner += \'; left: 0px;');
		phpads_2286.document.write(' top: 0px; visibility: hidden;"><'+'\'+\'img src=\\\'http:/\';\n\tphpa');
		phpads_2286.document.write('dsbanner += \'/66.235.180.59/Adserver/adlog.php?bannerid=2286');
		phpads_2286.document.write('&amp;clientid\';\n\tphpadsbanner += \'=131&amp;zoneid=972&amp;so');
		phpads_2286.document.write('urce=&amp;block=0&amp;capping=0&am\';\n\tphpadsbanner += \'p;cb=');
		phpads_2286.document.write('fe55adac3ff811ed6dde507d6804a034\\\' width=\\\'0\\\' height=\\\'0\\\' ');
		phpads_2286.document.write('\';\n\tphpadsbanner += \'alt=\\\'\\\' style=\\\'width: 0px; height: 0p');
		phpads_2286.document.write('x;\\\'><'+'\'+\'/div>\';\n\tdocument.write(\'<'+'\'+\'body leftmargin="0" to');
		phpads_2286.document.write('pmargin="0" marginwidth="0" marginheight="0">\');\n\tdocument.w');
		phpads_2286.document.write('rite(phpadsbanner);\n');
		phpads_2286.document.write('}');
		phpads_2286.document.write('<'+'/script>');

		phpads_2286.document.write('<'+'/head>');
		phpads_2286.document.write('<'+'body onLoad=\'showbanner()\'>');
		phpads_2286.document.write('<'+'/body><'+'/html>');
			
			phpads_2286.document.close();
		}

			phpads_2286.focus();
			}
	
	return true;
}


phpads_2286_pop();

