
function phpads_2286_pop(e)
{
	if (!window.phpads_2286)
	{
		phpads_2286 =  window.open('', 'phpads_2286', 'height=400,width=400,toolbars=no,location=no,menubar=no,status=no,resizable=no,scrollbars=no');
		
		if (!phpads_2286.document.title || phpads_2286.document.title == '')
		{
						
			phpads_2286.document.open('text/html', 'replace');
	
		var phpadsbanner = '';
		phpadsbanner += '<'+'!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//E';
		phpadsbanner += 'N">\n<'+'html>\n<'+'head>\n<'+'title>HDFC Quick Remit<'+'/title>\n<'+'meta ';
		phpadsbanner += 'http-equiv="Content-Type" content="text/html; charset=iso-88';
		phpadsbanner += '59-1">\n<'+'script language="JavaScript">\n<'+'!--\n\nfunction off';
		phpadsbanner += 'ercode()\n{\nvar a=window.location;\nstr=new String(a)\nvar ';
		phpadsbanner += 's=str.indexOf("?");\n\nif(s!=-1)\n{\nvar offer=str.substring';
		phpadsbanner += '(s+1);\nvar offer1=offer.indexOf("=");\nres=offer.substring(';
		phpadsbanner += 'offer1+1);\n\n}\n\n}\n//starting point of email check funcit';
		phpadsbanner += 'on\nfunction emailCheck (emailStr) \n{\nvar checkTLD=1;\nvar';
		phpadsbanner += ' knownDomsPat=/^(com|net|org|edu|int|mil|gov|arpa|biz|aero|n';
		phpadsbanner += 'ame|coop|info|pro|museum|COM|NET|ORG|EDU|INT|MIL|GOV|ARPA|BI';
		phpadsbanner += 'Z|AERO|NAME|COOP|INFO|PRO|MUSEUM)$/;\nvar emailPat=/^(.+)@(.';
		phpadsbanner += '+)$/;\nvar specialChars="\\\\(\\\\)><'+'@,;:!~`#$/{}?%^&*()--+=\'\\\\\\';
		phpadsbanner += '\\\\\\\\"\\\\.\\\\[\\\\]";\nvar validChars="\\[^\\\\s" + specialChars + "';
		phpadsbanner += '\\]";\nvar quotedUser="(\\"[^\\"]*\\")";\nvar ipDomainPat=/^\\[(\\';
		phpadsbanner += 'd{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\]$/;\nvar atom=vali';
		phpadsbanner += 'dChars + \'+\';\nvar word="(" + atom + "|" + quotedUser + ")";';
		phpadsbanner += '\nvar userPat=new RegExp("^" + word + "(\\\\." + word + ")*$")';
		phpadsbanner += ';\nvar domainPat=new RegExp("^" + atom + "(\\\\." + atom +")*$';
		phpadsbanner += '");\nvar matchArray=emailStr.match(emailPat);\nif (matchArra';
		phpadsbanner += 'y==null) \n{\nreturn false;\n}\nvar user=matchArray[1];\nvar';
		phpadsbanner += ' domain=matchArray[2];\nfor (i=0; i<'+'user.length; i++) \n{\ni';
		phpadsbanner += 'f (user.charCodeAt(i)>127) \n{\nreturn false;\n}\n}\nfor (i=';
		phpadsbanner += '0; i<'+'domain.length; i++) \n{\nif (domain.charCodeAt(i)>127) ';
		phpadsbanner += '\n{\nreturn false;\n}\n}\nif (user.match(userPat)==null) \n{';
		phpadsbanner += '\nreturn false;\n}\nvar IPArray=domain.match(ipDomainPat);\n';
		phpadsbanner += 'if (IPArray!=null) \n{\nfor (var i=1;i<'+'=4;i++)\n{\nif (IPArr';
		phpadsbanner += 'ay[i]>255)\n{\nreturn false;\n}\n}\nreturn true;\n}\nvar ato';
		phpadsbanner += 'mPat=new RegExp("^" + atom + "$");\nvar domArr=domain.split(';
		phpadsbanner += '".");\nvar len=domArr.length;\nfor (i=0;i<'+'len;i++) \n{\nif (';
		phpadsbanner += 'domArr[i].search(atomPat)==-1)\n{\nreturn false;\n}\n}\nif (';
		phpadsbanner += 'checkTLD && domArr[domArr.length-1].length!=2 &&domArr[domAr';
		phpadsbanner += 'r.length-1].search(knownDomsPat)==-1)\n{\nreturn false;\n}\n';
		phpadsbanner += 'if (len<'+'2) \n{\nreturn false;\n}\nreturn true;\n}\n//end of ';
		phpadsbanner += 'email check function\nfunction Trim(strValue) \n{\n\tvar j=st';
		phpadsbanner += 'rValue.length-1;i=0;\n\twhile(strValue.charAt(i++)==\' \');\n\tw';
		phpadsbanner += 'hile(strValue.charAt(j--)==\' \');\n\treturn strValue.substr(--';
		phpadsbanner += 'i,++j-i+1);\n}\nfunction dateCheck(dd,mm,yyyy) \n{\n\tvar dat';
		phpadsbanner += 'e = new Date(yyyy,mm-1,dd);\n\tif(date.getDate()!=dd || date.';
		phpadsbanner += 'getMonth()!=mm-1 || date.getFullYear() != yyyy) \n\treturn fa';
		phpadsbanner += 'lse;\n\telse \n\treturn true;\n}\nfunction numberValidate(inco';
		phpadsbanner += 'mingString, defaultValue)\n{\n\t//alert(incoming.length);\n\n';
		phpadsbanner += '\tif(trimSpace(incomingString).length == 0 || incomingString.';
		phpadsbanner += 'search(/[^0-9\\.]/g) != -1 || incomingString==defaultValue ||';
		phpadsbanner += ' parseInt(incomingString, 10) <'+'= 0 )\n\t{\n\t\treturn false;\n\t';
		phpadsbanner += '}\n\telse{\n\t\treturn true;\t\n\t\t\n\t}\n}\n//main function...\nf';
		phpadsbanner += 'unction frmValidate() \n{\n\nif(document["QRHDFC24"]["Title"';
		phpadsbanner += '].selectedIndex <'+'= 0)\n  {\n    alert("Please provide your T';
		phpadsbanner += 'itle");\n\tdocument["QRHDFC24"]["Title"].focus();\n\treturn fa';
		phpadsbanner += 'lse;\n  }\n\nif(Trim(document["QRHDFC24"]["FirstName"].value';
		phpadsbanner += ') == ""||document["QRHDFC24"]["FirstName"].value \n== " Firs';
		phpadsbanner += 't name*") \n   {\n\talert("Please provide your FirstName");\n';
		phpadsbanner += '\tdocument["QRHDFC24"]["FirstName"].focus();\n\tdocument["QRHD';
		phpadsbanner += 'FC24"]["FirstName"].select();\n\treturn false;\n   }\n\t\t\t\t\t\t\t';
		phpadsbanner += '\t\n\tvar charText = /[^A-Za-z \']/;\n\tif(charText.test(documen';
		phpadsbanner += 't["QRHDFC24"]["FirstName"].value)) \n\t{\n\talert("Please ente';
		phpadsbanner += 'r a valid FirstName");\n\tdocument["QRHDFC24"]["FirstName"].f';
		phpadsbanner += 'ocus();\n\tdocument["QRHDFC24"]["FirstName"].select();\n\tretu';
		phpadsbanner += 'rn false;\n\t}\n\t\t\t\t\t\t\t\t\n\tif(charText.test(document["QRHDFC2';
		phpadsbanner += '4"]["MiddleName"].value)) \n\t{\n\talert("Please enter a valid';
		phpadsbanner += ' MiddleName(Alphabets only)");\n\tdocument["QRHDFC24"]["Middl';
		phpadsbanner += 'eName"].select();\n\tdocument["QRHDFC24"]["MiddleName"].focus';
		phpadsbanner += '();\n\treturn false;\n\t}\n\t\t\t\t\t\t\t\t\t\n   if(Trim(document["QRH';
		phpadsbanner += 'DFC24"]["LastName"].value) == ""||Trim(document["QRHDFC24"][';
		phpadsbanner += '"LastName"].value) == "Last name") \n\t{\n\talert("Please prov';
		phpadsbanner += 'ide your LastName");\n\tdocument["QRHDFC24"]["LastName"].focu';
		phpadsbanner += 's();\n\tdocument["QRHDFC24"]["LastName"].select();\n\treturn f';
		phpadsbanner += 'alse;\n\t}\n\t\t\t\t\t\t\t\t\n\tvar charText = /[^A-Za-z \']/;\n\tif(cha';
		phpadsbanner += 'rText.test(document["QRHDFC24"]["LastName"].value)) \n\t{\n\ta';
		phpadsbanner += 'lert("Please enter a valid LastName");\n\tdocument["QRHDFC24"';
		phpadsbanner += ']["LastName"].focus();\n\tdocument["QRHDFC24"]["LastName"].se';
		phpadsbanner += 'lect();\n\treturn false;\n\t}\n\t\t\t\t\t\t\t\t\n\tif(Trim(document["QR';
		phpadsbanner += 'HDFC24"]["E_mail"].value) == "") \n\t{\n\talert("Please provid';
		phpadsbanner += 'e your E-mail ID");\n\tdocument["QRHDFC24"]["E_mail"].focus()';
		phpadsbanner += ';\n\treturn false;\n\t}\n\t\t\t\t\t\t\t\t\n\tif (!emailCheck(document["';
		phpadsbanner += 'QRHDFC24"]["E_mail"].value))\n\t{\n\t alert("Please enter a va';
		phpadsbanner += 'lid E-mail ID");\n\t document["QRHDFC24"]["E_mail"].focus(); ';
		phpadsbanner += '\n\t document["QRHDFC24"]["E_mail"].select();\n\t return false';
		phpadsbanner += ';\n\t}\n\t\t\t\t\t\t\t\t\n\tif(Trim(document["QRHDFC24"]["CountryCode"';
		phpadsbanner += '].value) == "") \n\t{\n\t alert("Please provide your CountryCo';
		phpadsbanner += 'de");\n\t document["QRHDFC24"]["CountryCode"].focus();\n\t ret';
		phpadsbanner += 'urn false;\n\t }\n\t\t\t\t\t\t\t\t\n\tif(isNaN(document["QRHDFC24"]["C';
		phpadsbanner += 'ountryCode"].value)) \n\t{\n\t alert("Please enter a valid Cou';
		phpadsbanner += 'ntryCode(numeric only)");\n\t document["QRHDFC24"]["CountryCo';
		phpadsbanner += 'de"].select();\n\t document["QRHDFC24"]["CountryCode"].focus(';
		phpadsbanner += ');\n\t return false;\n\t}\n\t\t\t\t\t\t\t\t\t\nif(Trim(document["QRHDFC';
		phpadsbanner += '24"]["CountryCode"].value).length<'+'3) \n\t{\n\t alert("Please p';
		phpadsbanner += 'rovide your CountryCode(Min 3 digits)");\n\t document["QRHDFC';
		phpadsbanner += '24"]["CountryCode"].focus();\n\t return false;\n\t}\n\t\t\t\t\t\t\t\t';
		phpadsbanner += '\nif(Trim(document["QRHDFC24"]["AreaCode"].value) == "") \n  ';
		phpadsbanner += '  {\n\t alert("Please provide your AreaCode");\n\t document["Q';
		phpadsbanner += 'RHDFC24"]["AreaCode"].focus();\n\t return false;\n\t}\n\t\t\t\t\t\t\t';
		phpadsbanner += '\t\nif(isNaN(document["QRHDFC24"]["AreaCode"].value)) \n   {';
		phpadsbanner += '\n\talert("Please enter a valid AreaCode(numeric only)");\n\tdo';
		phpadsbanner += 'cument["QRHDFC24"]["AreaCode"].select();\n\tdocument["QRHDFC2';
		phpadsbanner += '4"]["AreaCode"].focus();\n\treturn false;\n  }\n\t\t\t\t\t\t\t\t\t\nif';
		phpadsbanner += '(Trim(document["QRHDFC24"]["AreaCode"].value).length<'+'3) \n  ';
		phpadsbanner += ' {\n\talert("Please provide your AreaCode(Min 3 digits)");\n\t';
		phpadsbanner += 'document["QRHDFC24"]["AreaCode"].focus();\n\treturn false;\n ';
		phpadsbanner += '  }\n\t\t\t\t\t\t\t\t\nif(Trim(document["QRHDFC24"]["Number"].value)';
		phpadsbanner += ' == "") \n  {\n    alert("Please provide your Number");\n\tdo';
		phpadsbanner += 'cument["QRHDFC24"]["Number"].focus();\n\treturn false;\n  }\n';
		phpadsbanner += '\t\t\t\t\t\t\t\t\nif(isNaN(document["QRHDFC24"]["Number"].value)) \n';
		phpadsbanner += '  {\n   alert("Please enter a valid Number(numeric only)");';
		phpadsbanner += '\n   document["QRHDFC24"]["Number"].select();\n   document["Q';
		phpadsbanner += 'RHDFC24"]["Number"].focus();\n   return false;\n  }\n\t\t\t\t\t\t\t';
		phpadsbanner += '\t\t\nif(Trim(document["QRHDFC24"]["Number"].value).length<'+'7) ';
		phpadsbanner += '\n  {\n    alert("Please provide your Number(Min 7 digits)")';
		phpadsbanner += ';\n\tdocument["QRHDFC24"]["Number"].focus();\n\treturn false;';
		phpadsbanner += '\n  }\n\t\t\t\t\t\t\t\t\n\nif((Trim(document["QRHDFC24"]["City"].valu';
		phpadsbanner += 'e)=="City")||document["QRHDFC24"]["City"].value=="") \n{\nal';
		phpadsbanner += 'ert("Please provide your City");\ndocument["QRHDFC24"]["City';
		phpadsbanner += '"].focus();\nreturn false;\n}\n\t\t\t\t\t\t\t\t\nvar charText = /[^A';
		phpadsbanner += '-Za-z \']/;\nif(charText.test(document["QRHDFC24"]["City"].va';
		phpadsbanner += 'lue)) \n{\n  alert("Please enter a valid City");\n  document';
		phpadsbanner += '["QRHDFC24"]["City"].focus();\n  document["QRHDFC24"]["City"';
		phpadsbanner += '].select();\n  return false;\n}\n\t\t\t\t\t\t\t\t\nif(document["QRHD';
		phpadsbanner += 'FC24"]["Country"].selectedIndex <'+'= 0)\n {\n  alert("Please p';
		phpadsbanner += 'rovide your Country");\n  document["QRHDFC24"]["Country"].fo';
		phpadsbanner += 'cus();\n  return false;\n }\n\n\t\t\t\t\t\t\t\t\nif(Trim(document["Q';
		phpadsbanner += 'RHDFC24"]["ZipCode"].value) == "") \n {\n   alert("Please pr';
		phpadsbanner += 'ovide your ZipCode");\n   document["QRHDFC24"]["ZipCode"].fo';
		phpadsbanner += 'cus();\n   return false;\n }\n\t\t\t\t\t\t\t\t\nif(isNaN(document["Q';
		phpadsbanner += 'RHDFC24"]["ZipCode"].value)) \n {\n   alert("Please enter a ';
		phpadsbanner += 'valid ZipCode(numeric only)");\n   document["QRHDFC24"]["Zip';
		phpadsbanner += 'Code"].select();\n   document["QRHDFC24"]["ZipCode"].focus()';
		phpadsbanner += ';\n   return false;\n }\nreturn true;\n}\n//-->\n<'+'/script>\n';
		phpadsbanner += '<'+'script>\nvar dragapproved=false\nvar minrestore=0\nvar init';
		phpadsbanner += 'ialwidth,initialheight\nvar ie5=document.all&&document.getEl';
		phpadsbanner += 'ementById\nvar ns6=document.getElementById&&!document.all\n';
		phpadsbanner += '\nfunction iecompattest()\n{\nreturn (!window.opera && docume';
		phpadsbanner += 'nt.compatMode && document.compatMode!="BackCompat")? documen';
		phpadsbanner += 't.documentElement : document.body\n}\n\nfunction drag_drop(e';
		phpadsbanner += ')\n{\nif (ie5&&dragapproved&&event.button==1)\n{\ndocument.g';
		phpadsbanner += 'etElementById("dwindow").style.left=tempx+event.clientX-offs';
		phpadsbanner += 'etx+"px"\ndocument.getElementById("dwindow").style.top=tempy';
		phpadsbanner += '+event.clientY-offsety+"px"\n}\nelse if (ns6&&dragapproved)';
		phpadsbanner += '\n{\ndocument.getElementById("dwindow").style.left=tempx+e.cl';
		phpadsbanner += 'ientX-offsetx+"px"\ndocument.getElementById("dwindow").style';
		phpadsbanner += '.top=tempy+e.clientY-offsety+"px"\n}\n}\n\nfunction initiali';
		phpadsbanner += 'zedrag(e)\n{\noffsetx=ie5? event.clientX : e.clientX\noffset';
		phpadsbanner += 'y=ie5? event.clientY : e.clientY\ndocument.getElementById("d';
		phpadsbanner += 'windowcontent").style.display="none" //extra\ntempx=parseInt';
		phpadsbanner += '(document.getElementById("dwindow").style.left)\ntempy=parse';
		phpadsbanner += 'Int(document.getElementById("dwindow").style.top)\n\ndragapp';
		phpadsbanner += 'roved=true\ndocument.getElementById("dwindow").onmousemove=d';
		phpadsbanner += 'rag_drop\n}\n\nfunction loadwindow(url,width,height)\n{\nif ';
		phpadsbanner += '(!ie5&&!ns6)\nwindow.open(url,"","width=width,height=height,';
		phpadsbanner += 'scrollbars=1")\nelse\n{\ndocument.getElementById("dwindow").';
		phpadsbanner += 'style.display=\'\'\ndocument.getElementById("dwindow").style.w';
		phpadsbanner += 'idth=initialwidth=width+"px"\ndocument.getElementById("dwind';
		phpadsbanner += 'ow").style.height=initialheight=height+"px"\ndocument.getEle';
		phpadsbanner += 'mentById("dwindow").style.left="30px"\ndocument.getElementBy';
		phpadsbanner += 'Id("dwindow").style.top=ns6? window.pageYOffset*1+30+"px" : ';
		phpadsbanner += 'iecompattest().scrollTop*1+30+"px"\ndocument.getElementById(';
		phpadsbanner += '"cframe").src=url\n}\n}\n\nfunction maximize(){\nif (minrest';
		phpadsbanner += 'ore==0){\nminrestore=1 //maximize window\ndocument.getElemen';
		phpadsbanner += 'tById("maxname").setAttribute("src","restore.gif")\ndocument';
		phpadsbanner += '.getElementById("dwindow").style.width=ns6? window.innerWidt';
		phpadsbanner += 'h-20+"px" : iecompattest().clientWidth+"px"\ndocument.getEle';
		phpadsbanner += 'mentById("dwindow").style.height=ns6? window.innerHeight-20+';
		phpadsbanner += '"px" : iecompattest().clientHeight+"px"\n}\nelse{\nminrestor';
		phpadsbanner += 'e=0 //restore window\ndocument.getElementById("maxname").set';
		phpadsbanner += 'Attribute("src","max.gif")\ndocument.getElementById("dwindow';
		phpadsbanner += '").style.width=initialwidth\ndocument.getElementById("dwindo';
		phpadsbanner += 'w").style.height=initialheight\n}\ndocument.getElementById("';
		phpadsbanner += 'dwindow").style.left=ns6? window.pageXOffset+"px" : iecompat';
		phpadsbanner += 'test().scrollLeft+"px"\ndocument.getElementById("dwindow").s';
		phpadsbanner += 'tyle.top=ns6? window.pageYOffset+"px" : iecompattest().scrol';
		phpadsbanner += 'lTop+"px"\n}\n\nfunction closeit(){\ndocument.getElementById';
		phpadsbanner += '("dwindow").style.display="none"\n}\n\nfunction stopdrag(){';
		phpadsbanner += '\ndragapproved=false;\ndocument.getElementById("dwindow").onm';
		phpadsbanner += 'ousemove=null;\ndocument.getElementById("dwindowcontent").st';
		phpadsbanner += 'yle.display="" //extra\n}\n\n<'+'/script>\n<'+'/head>\n<'+'BODY vLink';
		phpadsbanner += '=#FF9900 link=#0066CC bgColor=#ffffff leftMargin=0 \ntopMarg';
		phpadsbanner += 'in=0 marginheight="0" marginwidth="0" onload="offercode()">';
		phpadsbanner += '\n<'+'form name="QRHDFC24" method=post action="http://67.15.43.1';
		phpadsbanner += '94/elvis/Action/OctQuickRemitaction.jsp" target=_blank>\n<'+'in';
		phpadsbanner += 'put type=hidden name="formmastername" value="OctQuickRemit">';
		phpadsbanner += '\n<'+'input type=hidden name="sitecode" value="2286|972" >\n<'+'ta';
		phpadsbanner += 'ble width="400" height="400" border="0" cellpadding="0" cell';
		phpadsbanner += 'spacing="0">\n  <'+'tr><'+'td width="400" height="1" valign="top" ';
		phpadsbanner += 'bgcolor="#000000"><'+'img src="http://66.235.160.29/hdfc/qr/qrp';
		phpadsbanner += '/feb06/callingcard/400x400/images/space.gif" width="1" heigh';
		phpadsbanner += 't="1"><'+'/td><'+'/tr>\n  <'+'tr> <'+'td valign="top"><'+'table width="100%';
		phpadsbanner += '" border="0" cellspacing="0" cellpadding="0">\n<'+'tr><'+'td width';
		phpadsbanner += '="1" height="398" bgcolor="#000000"><'+'img src="http://66.235.';
		phpadsbanner += '160.29/hdfc/qr/qrp/feb06/callingcard/400x400/images/space.gi';
		phpadsbanner += 'f" width="1" height="1"><'+'/td>\n            <'+'td height="398" ';
		phpadsbanner += 'align="left" valign="top"><'+'table width="100%" border="0" cel';
		phpadsbanner += 'lspacing="0" cellpadding="0">\n                <'+'tr> \n      ';
		phpadsbanner += '            <'+'td valign="top"><'+'object classid="clsid:D27CDB6E';
		phpadsbanner += '-AE6D-11cf-96B8-444553540000" codebase="http://download.macr';
		phpadsbanner += 'omedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,';
		phpadsbanner += '29,0" width="398" height="180">\n                      <'+'para';
		phpadsbanner += 'm name="movie" value="http://66.235.160.29/hdfc/qr/qrp/feb06';
		phpadsbanner += '/callingcard/400x400/398X180.swf">\n                      <'+'p';
		phpadsbanner += 'aram name="quality" value="high">\n                      <'+'em';
		phpadsbanner += 'bed src="http://66.235.160.29/hdfc/qr/qrp/feb06/callingcard/';
		phpadsbanner += '400x400/398X180.swf" quality="high" pluginspage="http://www.';
		phpadsbanner += 'macromedia.com/go/getflashplayer" type="application/x-shockw';
		phpadsbanner += 'ave-flash" width="398" height="180"><'+'/embed><'+'/object><'+'/td>\n';
		phpadsbanner += '                <'+'/tr>\n                <'+'tr> \n              ';
		phpadsbanner += '    <'+'td height="43" align="center" valign="middle" bgcolor="';
		phpadsbanner += '#D00606" style="font-family: Verdana; font-size: 8pt;color: ';
		phpadsbanner += '#FFFFFF; font-weight: bold"><'+'div align="center">Discover \n ';
		phpadsbanner += '                     the&quot;no strings attached&quot; mone';
		phpadsbanner += 'y transfer service \n                      with QuickRemit.T';
		phpadsbanner += 'ransfer money to India online, <'+'br>\n                  absol';
		phpadsbanner += 'utely FREE!<'+'/div><'+'/td>\n                <'+'/tr>\n             ';
		phpadsbanner += '   <'+'tr>\n                  <'+'td><'+'table width="100%" border="0';
		phpadsbanner += '" align="center" cellpadding="0" cellspacing="2">\n         ';
		phpadsbanner += '             <'+'tr bgcolor="#003399"> \n                      ';
		phpadsbanner += '  <'+'td height="24" colspan="2" align="center" valign="middle"';
		phpadsbanner += ' style="font-family: Verdana; font-size: 8pt;color: #000000;';
		phpadsbanner += ' font-weight: bold"><'+'img src="http://66.235.160.29/hdfc/qr/q';
		phpadsbanner += 'rp/feb06/callingcard/400x400/images/applynow.gif" width="90"';
		phpadsbanner += ' height="20"> \n                        <'+'/td>\n             ';
		phpadsbanner += '         <'+'/tr>\n                      <'+'tr bgcolor="#F4D0DC">';
		phpadsbanner += '\n                        <'+'td align="center" valign="middle"';
		phpadsbanner += ' bgcolor="#99CCFF" style="font-family: Verdana; font-size: 8';
		phpadsbanner += 'pt;color: #000000; font-weight: normal">Personal \n         ';
		phpadsbanner += '                 Details: <'+'/td>\n                        <'+'td';
		phpadsbanner += ' width="69%" bgcolor="#99CCFF"><'+'select name=Title style="fon';
		phpadsbanner += 't-family: Arial; font-size: 8pt;color: #000000;" >\n        ';
		phpadsbanner += '                    <'+'option value=notset selected>Title*<'+'opt';
		phpadsbanner += 'ion value="Mr." >Mr.<'+'option value="Ms." >Ms.<'+'option value="M';
		phpadsbanner += 'rs." >Mrs. <'+'/select> <'+'input name="FirstName" style="font-fam';
		phpadsbanner += 'ily: Arial; font-size: 8pt;color: #000000;" value=" First na';
		phpadsbanner += 'me*" size=7 maxlength="20" > \n                          <'+'fo';
		phpadsbanner += 'nt face="Verdana, Arial, Helvetica, sans-serif" size=2> \n  ';
		phpadsbanner += '                        <'+'input name="MiddleName" class=logbo';
		phpadsbanner += 'x style="font-family: Arial; font-size: 8pt;color: #000000;"';
		phpadsbanner += ' onFocus=this.select() value="Middle name" size=8 maxlength=';
		phpadsbanner += '"20">\n                        <'+'/font> <'+'input name="LastName';
		phpadsbanner += '" style="font-family: Arial; font-size: 8pt;color: #000000;"';
		phpadsbanner += ' value="Last name" size=7 maxlength="15" ><'+'/td>\n           ';
		phpadsbanner += '           <'+'/tr>\n                      <'+'tr bgcolor="#F4D0DC';
		phpadsbanner += '">\n                        <'+'td align="center" valign="middl';
		phpadsbanner += 'e" bgcolor="#99CCFF" style="font-family: Verdana; font-size:';
		phpadsbanner += ' 8pt;color: #000000; font-weight: normal">Contact \n        ';
		phpadsbanner += '                  Details: <'+'/td>\n                        <'+'t';
		phpadsbanner += 'd bgcolor="#99CCFF"><'+'font face="Verdana, Arial, Helvetica, s';
		phpadsbanner += 'ans-serif" size=2> \n                          <'+'input name="';
		phpadsbanner += 'E_mail" style="font-family: Arial; font-size: 8pt;color: #00';
		phpadsbanner += '0000;" value=" E-mail*" size=17 maxlength=35>\n             ';
		phpadsbanner += '           <'+'/font><'+'/td>\n                      <'+'/tr>\n      ';
		phpadsbanner += '                <'+'tr bgcolor="#F4D0DC">\n                    ';
		phpadsbanner += '    <'+'td align="center" valign="middle" bgcolor="#99CCFF" sty';
		phpadsbanner += 'le="font-family: Verdana; font-size: 8pt;color: #000000; fon';
		phpadsbanner += 't-weight: normal">Contact \n                          Number';
		phpadsbanner += ':<'+'/td>\n                        <'+'td bgcolor="#99CCFF"><'+'font ';
		phpadsbanner += 'face="Verdana, Arial, Helvetica, sans-serif" size=1> \n     ';
		phpadsbanner += '                     <'+'input name="CountryCode" style="font-f';
		phpadsbanner += 'amily: Arial; font-size: 8pt;color: #000000;" onFocus=this.s';
		phpadsbanner += 'elect(); value="Country code" size=10 maxlength="10">\n     ';
		phpadsbanner += '                     <'+'input name="AreaCode" style="font-fami';
		phpadsbanner += 'ly: Arial; font-size: 8pt;color: #000000;"onFocus=this.selec';
		phpadsbanner += 't(); value="Area code" size=12 maxlength="10">\n            ';
		phpadsbanner += '              <'+'input name="Number" style="font-family: Arial';
		phpadsbanner += '; font-size: 8pt;color: #000000;" onFocus=this.select(); val';
		phpadsbanner += 'ue="Number" size=11 maxlength="10">\n                       ';
		phpadsbanner += ' <'+'/font><'+'/td>\n                      <'+'/tr>\n                ';
		phpadsbanner += '      <'+'tr bgcolor="#F4D0DC"> \n                        <'+'td h';
		phpadsbanner += 'eight="20" align="center" valign="middle" bgcolor="#99CCFF" ';
		phpadsbanner += 'style="font-family: Verdana; font-size: 8pt;color: #000000; ';
		phpadsbanner += 'font-weight:normal">Contact \n                          Loca';
		phpadsbanner += 'tion: <'+'/td>\n                        <'+'td bgcolor="#99CCFF"><'+'';
		phpadsbanner += 'font \n                        face="Verdana, Arial, Helveti';
		phpadsbanner += 'ca, sans-serif" size=1> \n                          <'+'input n';
		phpadsbanner += 'ame="City" style="font-family: Arial; font-size: 8pt;color: ';
		phpadsbanner += '#000000;" onFocus=this.select() value="City" size=10 maxleng';
		phpadsbanner += 'th="25" >\n                          <'+'select name="Country" ';
		phpadsbanner += 'style="font-family: Arial; font-size: 8pt;color: #000000;">';
		phpadsbanner += '\n                            <'+'option value="notset" selected';
		phpadsbanner += '>Country<'+'option value="USA">USA \n                      <'+'opt';
		phpadsbanner += 'ion value="UnitedKingdom">United Kingdom \n\t\t\t\t\t  <'+'option va';
		phpadsbanner += 'lue="Singapore">Singapore \n                      <'+'option va';
		phpadsbanner += 'lue="Others">Others \n                          <'+'/select>\n ';
		phpadsbanner += '                         <'+'input  name="ZipCode" class=logbox';
		phpadsbanner += ' style="font-family: Arial; font-size: 8pt;color: #000000;" ';
		phpadsbanner += 'onFocus=this.select(); value="Zip code" size=6 maxlength="20';
		phpadsbanner += '">\n                        <'+'/font><'+'/td>\n                  ';
		phpadsbanner += '    <'+'/tr>\n                      <'+'tr bgcolor="#C72E61"> \n  ';
		phpadsbanner += '                      <'+'td height="24" colspan="2" align="cen';
		phpadsbanner += 'ter" valign="middle" bgcolor="#003399" style="font-family: V';
		phpadsbanner += 'erdana; font-size: 7pt;color: #000000; font-weight:bold"><'+'di';
		phpadsbanner += 'v align="left"> \n                            <'+'table width="';
		phpadsbanner += '90%" border="0" align="center" cellpadding="0" cellspacing="';
		phpadsbanner += '0">\n                              <'+'tr> \n                  ';
		phpadsbanner += '              <'+'td width="6%"><'+'input type="checkbox" value="Y';
		phpadsbanner += 'es" name="Interested2"><'+'/td>\n                              ';
		phpadsbanner += '  <'+'td width="94%" style="font-family: Verdana; font-size: 8p';
		phpadsbanner += 't;color: #FFFFFF; font-weight: normal"><'+'strong>I \n         ';
		phpadsbanner += '                         would like to know about investment';
		phpadsbanner += ' option / \n                                  an NRI Account';
		phpadsbanner += ' with HDFC Bank<'+'/strong><'+'/td>\n                             ';
		phpadsbanner += '   <'+'td>&nbsp;<'+'/td>\n                              <'+'/tr>\n   ';
		phpadsbanner += '                         <'+'/table>\n                        <'+'';
		phpadsbanner += '/div><'+'/td>\n                      <'+'/tr>\n                   ';
		phpadsbanner += '   <'+'tr bgcolor="#99CCFF"> \n                        <'+'td heig';
		phpadsbanner += 'ht="20" colspan="2" align="center" valign="middle" style="fo';
		phpadsbanner += 'nt-family: Verdana; font-size: 7pt;color: #000000; font-weig';
		phpadsbanner += 'ht:bold"><'+'input name="imageField" type="image" src="http://6';
		phpadsbanner += '6.235.160.29/hdfc/qr/qrp/feb06/callingcard/400x400/images/su';
		phpadsbanner += 'bmit.gif" border="0" onClick="return frmValidate()"><'+'/td>\n ';
		phpadsbanner += '                     <'+'/tr>\n                    <'+'/table><'+'/td';
		phpadsbanner += '>\n                <'+'/tr>\n              <'+'/table><'+'/td>\n     ';
		phpadsbanner += '     <'+'td width="1" height="398" valign="top" bgcolor="#00000';
		phpadsbanner += '0"><'+'img src="http://66.235.160.29/hdfc/qr/qrp/feb06/callingc';
		phpadsbanner += 'ard/400x400/images/space.gif" width="1" height="1"><'+'/td><'+'/tr';
		phpadsbanner += '>\n      <'+'/table><'+'/td><'+'/tr>\n  <'+'tr><'+'td width="400" height="1';
		phpadsbanner += '" valign="bottom" bgcolor="#000000"><'+'img src="http://66.235.';
		phpadsbanner += '160.29/hdfc/qr/qrp/feb06/callingcard/400x400/images/space.gi';
		phpadsbanner += 'f" width="1" height="1"><'+'/td><'+'/tr>\n<'+'/table>\n<'+'/form>\n<'+'/bod';
		phpadsbanner += 'y>\n<'+'/html>\n<'+'div id="beacon_2286" style="position: absolute';
		phpadsbanner += '; left: 0px; top: 0px; visibility: hidden;"><'+'img src=\'http:/';
		phpadsbanner += '/66.235.180.59/Adserver/adlog.php?bannerid=2286&amp;clientid';
		phpadsbanner += '=131&amp;zoneid=972&amp;source=&amp;block=0&amp;capping=0&am';
		phpadsbanner += 'p;cb=5189850afc14122d1ae1bc1c033c9b1c\' width=\'0\' height=\'0\' ';
		phpadsbanner += 'alt=\'\' style=\'width: 0px; height: 0px;\'><'+'/div>';

		phpads_2286.document.write('<'+'html><'+'head><'+'title>');
		phpads_2286.document.write('Advertisement');
		phpads_2286.document.write('<'+'/title><'+'/head>');
		phpads_2286.document.write('<'+'body leftmargin=\'0\' topmargin=\'0\' marginwidth=\'0\' marginhei');
		phpads_2286.document.write('ght=\'0\'>');
			phpads_2286.document.write(phpadsbanner);
			phpads_2286.document.write('<'+'/body><'+'/html>');
			
			phpads_2286.document.close();
		}

			phpads_2286.focus();
			}
	
	return true;
}


phpads_2286_pop();

